openapi: 3.0.0
info:
  title: Node MYSQL
  contact: {}
  version: '1.0'
servers:
  - url: http://127.0.0.1:3004/api/
    variables: {}
paths:
  /users:
    get:
      tags:
        - Users
      summary: Get All Users
      operationId: GetAllUsers
      parameters: []
      responses:
        '200':
          description: ''
          headers: {}
      deprecated: false
